export const CarDetails = [
  {
    name: "Audi A1 S-Line",
    model: "Audi",
    mark: "A1",
    rent: "45",
    year: "2012",
    doors: "4/5",
    ac: "Yes",
    transmission: "Manual",
    fuel: "Gasoline",
    image: "/Images/cars/audi.jpeg",
  },
  {
    name: "VW Golf 6",
    model: "Golf 6",
    mark: "Volkswagen",
    rent: "37",
    year: "2008",
    doors: "4/5",
    ac: "Yes",
    transmission: "Manual",
    fuel: "Diesel",
    image: "/Images/cars/vw1.jpg",
  },
  {
    name: "Toyota Camry",
    model: "Camry",
    mark: "Toyota",
    rent: "30",
    year: "2006",
    doors: "4/5",
    ac: "Yes",
    transmission: "Automatic",
    fuel: "Hybrid",
    image: "/Images/cars/toyota.jpg",
  },
  {
    name: "BMW 320 ModernLine",
    model: "320",
    mark: "BMW",
    rent: "35",
    year: "2012",
    doors: "4/5",
    ac: "Yes",
    transmission: "Manual",
    fuel: "Diesel",
    image: "/Images/cars/bmw.jpg",
  },
  {
    name: "Mercedes-Benz GLK",
    model: "Benz GLK",
    mark: "Mercedes",
    rent: "50",
    year: "2006",
    doors: "4/5",
    ac: "Yes",
    transmission: "Manual",
    fuel: "Diesel",
    image: "/Images/cars/mercedes.jpg",
  },
  {
    name: "VW Passat CC",
    model: "Passat CC",
    mark: "Volkswagen",
    rent: "25",
    year: "2008",
    doors: "4/5",
    ac: "Yes",
    transmission: "Automatic",
    fuel: "Gasoline",
    image: "/Images/cars/vw2.jpg",
  },
];
